"""Command-line interface for Signal Analytics Sandbox."""

from __future__ import annotations

from pathlib import Path

import click

from signal_sandbox.artifact_pipeline import (
    build_capture_pack,
    build_outcome_prep_pack,
    build_review_closure_pack,
    build_source_report_input,
    load_capture_pack,
    load_outcome_prep_pack,
    load_review_closure_pack,
)
from signal_sandbox.auto_validation import AutoValidationEvidenceBundle
from signal_sandbox.config import get_workspace
from signal_sandbox.media import (
    MediaManifest,
    MediaModality,
    OpenAIWhisperTranscriptionClient,
    run_whisper_transcription,
)
from signal_sandbox.media.transcription import TRANSCRIPTION_ENABLE_ENV
from signal_sandbox.santiment import (
    SANTIMENT_API_KEY_ENV,
    SANTIMENT_ENABLE_ENV,
    SantimentGraphQLClient,
    build_santiment_context_artifact,
    export_santiment_context_artifact,
)

PLANNED_SUBCOMMANDS = (
    "init-workspace",
    "add-source",
    "extract",
    "review",
    "snapshot",
    "match",
    "report",
    "santiment-context",
    "transcribe-media",
    "status",
)


def _not_implemented() -> None:
    click.echo("not implemented", err=True)
    raise click.exceptions.Exit(2)


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
def main() -> None:
    """Audit public signal sources with deterministic local workflows."""


@main.command("init-workspace", help="Initialize a local operator workspace.")
def init_workspace() -> None:
    _not_implemented()


@main.command("add-source", help="Add a public source manifest.")
def add_source() -> None:
    _not_implemented()


@main.command("extract", help="Extract signal drafts from captured posts.")
@click.option("--source-id", required=True, help="Source/channel ID to process.")
@click.option(
    "--workspace",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=None,
    help="Workspace root. Defaults to SIGNAL_SANDBOX_WORKSPACE or ./workspace.",
)
@click.option(
    "--pseudo-labels",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    default=None,
    help="Optional JSONL pseudo-label file to validate and join.",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=Path("docs/pilot"),
    show_default=True,
    help="Directory for generated review artifacts.",
)
def extract(
    source_id: str,
    workspace: Path | None,
    pseudo_labels: Path | None,
    output_dir: Path,
) -> None:
    workspace_path = workspace or get_workspace()
    pack = build_capture_pack(
        workspace=workspace_path,
        source_id=source_id,
        pseudo_label_path=pseudo_labels,
    )
    markdown_path = output_dir / f"{source_id}_CAPTURE_PACK.md"
    json_path = output_dir / f"{source_id}_CAPTURE_PACK.json"
    pack.write_markdown(markdown_path)
    pack.write_json(json_path)
    click.echo(f"capture pack rows: {len(pack.rows)}")
    click.echo(f"markdown: {markdown_path}")
    click.echo(f"json: {json_path}")


@main.command("review", help="Review extraction drafts before ledger approval.")
@click.option(
    "--capture-pack",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="Capture pack JSON generated by `signal-sandbox extract`.",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=Path("docs/pilot"),
    show_default=True,
    help="Directory for generated review artifacts.",
)
def review(capture_pack: Path, output_dir: Path) -> None:
    pack = load_capture_pack(capture_pack)
    closure = build_review_closure_pack(pack)
    markdown_path = output_dir / f"{pack.source_id}_REVIEW_QUEUE_CLOSED.md"
    json_path = output_dir / f"{pack.source_id}_REVIEW_QUEUE_CLOSED.json"
    closure.write_markdown(markdown_path)
    closure.write_json(json_path)
    click.echo(f"review rows: {len(closure.rows)}")
    click.echo(f"eligible rows: {closure.eligible_count()}")
    click.echo(f"markdown: {markdown_path}")
    click.echo(f"json: {json_path}")


@main.command("snapshot", help="Create or load a price-data snapshot.")
@click.option(
    "--review-queue",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="Review closure JSON generated by `signal-sandbox review`.",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=Path("docs/pilot"),
    show_default=True,
    help="Directory for generated outcome prep artifacts.",
)
def snapshot(review_queue: Path, output_dir: Path) -> None:
    review_pack = load_review_closure_pack(review_queue)
    prep = build_outcome_prep_pack(review_pack)
    markdown_path = output_dir / f"{review_pack.source_id}_OUTCOME_PREP.md"
    json_path = output_dir / f"{review_pack.source_id}_OUTCOME_PREP.json"
    prep.write_markdown(markdown_path)
    prep.write_json(json_path)
    click.echo(f"outcome rows: {len(prep.rows)}")
    click.echo(f"market-data fetches: {prep.market_data_fetch_count()}")
    click.echo(f"markdown: {markdown_path}")
    click.echo(f"json: {json_path}")


@main.command("match", help="Match approved signals against a price snapshot.")
def match() -> None:
    _not_implemented()


@main.command("report", help="Render a Markdown audit report.")
@click.option(
    "--capture-pack",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="Capture pack JSON generated by `signal-sandbox extract`.",
)
@click.option(
    "--review-queue",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="Review closure JSON generated by `signal-sandbox review`.",
)
@click.option(
    "--outcome-prep",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="Outcome prep JSON generated by `signal-sandbox snapshot`.",
)
@click.option(
    "--output",
    type=click.Path(path_type=Path, dir_okay=False),
    default=Path("docs/pilot/reports/bablos79_SIGNAL_REPORT_V1.md"),
    show_default=True,
    help="Report Markdown output path.",
)
def report(
    capture_pack: Path,
    review_queue: Path,
    outcome_prep: Path,
    output: Path,
) -> None:
    report_input = build_source_report_input(
        capture_pack=load_capture_pack(capture_pack),
        review_pack=load_review_closure_pack(review_queue),
        outcome_pack=load_outcome_prep_pack(outcome_prep),
    )
    report_input.write_markdown(output)
    click.echo(f"report: {output}")


@main.command(
    "santiment-context",
    help="Fetch Santiment context for an auto-validation evidence bundle.",
)
@click.option(
    "--bundle",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="AutoValidationEvidenceBundle JSON artifact.",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=Path("docs/pilot/santiment"),
    show_default=True,
    help="Directory for Santiment context JSON/Markdown artifacts.",
)
@click.option(
    "--approve",
    is_flag=True,
    help="Required per-run approval gate for Santiment provider calls.",
)
@click.option(
    "--interval",
    default="1d",
    show_default=True,
    help="Santiment timeseries interval.",
)
@click.option(
    "--lookback-days",
    default=7,
    show_default=True,
    type=int,
    help="Days before the Telegram post to include.",
)
@click.option(
    "--forward-days",
    default=7,
    show_default=True,
    type=int,
    help="Days after the Telegram post to include.",
)
def santiment_context(
    bundle: Path,
    output_dir: Path,
    approve: bool,
    interval: str,
    lookback_days: int,
    forward_days: int,
) -> None:
    if not approve:
        click.echo("approval: missing --approve", err=True)
        raise click.exceptions.Exit(2)
    if not _santiment_env_enabled():
        click.echo(f"environment: set {SANTIMENT_ENABLE_ENV}=1", err=True)
        raise click.exceptions.Exit(2)
    if not _santiment_api_key_present():
        click.echo(f"environment: set {SANTIMENT_API_KEY_ENV}", err=True)
        raise click.exceptions.Exit(2)

    evidence_bundle = AutoValidationEvidenceBundle.model_validate_json(
        bundle.read_text(encoding="utf-8")
    )
    artifact = build_santiment_context_artifact(
        bundle=evidence_bundle,
        provider=SantimentGraphQLClient(),
        interval=interval,
        lookback_days=lookback_days,
        forward_days=forward_days,
    )
    export = export_santiment_context_artifact(artifact, output_dir=output_dir)
    click.echo(f"candidate: {artifact.candidate_id}")
    click.echo(f"asset: {artifact.asset}")
    click.echo(f"santiment_slug: {artifact.santiment_slug}")
    click.echo(f"json: {export.json_path}")
    click.echo(f"markdown: {export.markdown_path}")
    click.echo(f"artifact_sha256: {export.artifact_sha256}")


@main.command(
    "transcribe-media",
    help="Create draft Whisper transcripts for voice/audio media manifest rows.",
)
@click.option(
    "--media-manifest",
    type=click.Path(path_type=Path, dir_okay=False, exists=True),
    required=True,
    help="Media manifest JSON containing local voice/audio artifacts.",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=Path("docs/pilot/transcripts"),
    show_default=True,
    help="Directory for draft transcript JSON artifacts.",
)
@click.option(
    "--model",
    default="whisper-1",
    show_default=True,
    help="Managed Whisper model name.",
)
@click.option(
    "--approve",
    is_flag=True,
    help="Required per-run approval gate for provider transcription.",
)
@click.option(
    "--delete-raw-on-success",
    is_flag=True,
    help="Delete local raw media after successful draft transcript creation.",
)
def transcribe_media(
    media_manifest: Path,
    output_dir: Path,
    model: str,
    approve: bool,
    delete_raw_on_success: bool,
) -> None:
    manifest = MediaManifest.model_validate_json(
        media_manifest.read_text(encoding="utf-8")
    )
    client = OpenAIWhisperTranscriptionClient()
    voice_rows = [
        row
        for row in manifest.rows
        if row.modality in {MediaModality.VOICE, MediaModality.AUDIO}
    ]
    results = [
        run_whisper_transcription(
            row,
            client=client,
            output_dir=output_dir,
            per_run_approved=approve,
            model=model,
            delete_raw_on_success=delete_raw_on_success,
        )
        for row in voice_rows
    ]

    draft_count = sum(1 for result in results if result.transcript is not None)
    skipped_count = sum(1 for result in results if result.skipped_reason is not None)
    failed_count = sum(1 for result in results if result.error_type is not None)
    click.echo(f"voice/audio rows: {len(voice_rows)}")
    click.echo(f"draft transcripts: {draft_count}")
    click.echo(f"skipped: {skipped_count}")
    click.echo(f"provider failures: {failed_count}")
    if not approve:
        click.echo("approval: missing --approve", err=True)
    if not _transcription_env_enabled():
        click.echo(f"environment: set {TRANSCRIPTION_ENABLE_ENV}=1", err=True)
    for result in results:
        if result.transcript is not None:
            click.echo(f"{result.media_id}: {result.transcript.artifact_path}")
        elif result.skipped_reason is not None:
            click.echo(f"{result.media_id}: skipped:{result.skipped_reason}")
        elif result.error_type is not None:
            click.echo(f"{result.media_id}: provider_failed:{result.error_type}")


@main.command("status", help="Show local configuration status.")
def status() -> None:
    click.echo(f"status: ok\nworkspace: {get_workspace()}")


def _transcription_env_enabled() -> bool:
    import os

    return os.environ.get(TRANSCRIPTION_ENABLE_ENV, "").strip() == "1"


def _santiment_env_enabled() -> bool:
    import os

    return os.environ.get(SANTIMENT_ENABLE_ENV, "").strip() == "1"


def _santiment_api_key_present() -> bool:
    import os

    return bool(os.environ.get(SANTIMENT_API_KEY_ENV, "").strip())


if __name__ == "__main__":
    main()
